### ISSUE TITLE
Gym env version?

### ISSUE THREAD

**Issue by edwhu** [google-research/robopianist#10]
Hi, 

Is there a `gym` or `gymnasium` version of the tasks as mentioned in the paper?

<img width="498" alt="Screen Shot 2023-05-25 at 4 17 38 PM" src="https://github.com/google-research/robopianist/assets/13341926/715830da-b0d5-4961-8bca-521a3b1a2904">

**Comment by kevinzakka** [comment]
Hi @hueds, you should be able to convert it to a `gym` environment using [dmc2gym](https://github.com/ikostrikov/dmcgym). Let me know if you run into issues.
