### ISSUE TITLE
Availability of Training Codes

### ISSUE THREAD

**Issue by Minyoung1005** [google-research/robopianist#12]
Hi,

I love your work and would like to use this benchmark for my RL research.
I want to reproduce DroQ and PPO results illustrated in Figure 4 in your paper.

Do you have any plans to release the training codes?
I would also appreciate it if you could provide the pre-trained models.

**Comment by kevinzakka** [comment]
Hi @Minyoung1005, I'll try to get around releasing the RL code soon, hopefully within this month.

**Comment by Minyoung1005** [comment]
I'm excited to hear that you're planning to release the RL code soon. I look forward to exploring the code once it's available.

**Comment by kevinzakka** [comment]
Hi @Minyoung1005, see https://github.com/kevinzakka/robopianist-rl for the RL training code.

**Comment by Minyoung1005** [comment]
@kevinzakka Thank you! Checked the new repo :)
