### ISSUE TITLE
Play midi script takes a while to load and play the midi file.

### ISSUE THREAD

**Issue by edwhu** [google-research/robopianist#6]
Hi, I'm running this on my M1 mac.

`python examples/play_midi_file.py --file robopianist/music/data/rousseau/twinkle-twinkle-trimmed.mid`

It takes about ~20 seconds before audio playback starts. Is this normal?

**Comment by kevinzakka** [comment]
Hey @hueds, yup, those songs have an initial silence (from the recording). We trim the silence when we convert to a trajectory but currently doesn’t happen for pure playback.
