### ISSUE TITLE
OSError from libwayland-client

### ISSUE THREAD

**Issue by hturner08** [google-research/robopianist#8]
I installeded from source on WSL2 running Ubuuntu 20.04. The installation throws no warnings or errors but when I try to run "make test" or the tutorial notebook and import robopianist I get the following error:
```
ERROR robopianist/suite/tasks/self_actuated_piano_test.py - OSError: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0
```

**Comment by kevinzakka** [comment]
Hi, could you see if #4 is helpful?

**Comment by hturner08** [comment]
Sorry just saw FAQ
