### ISSUE TITLE
Adding variable velocity to outputted MIDI notes

### ISSUE THREAD

**Issue by hturner08** [google-research/robopianist#9]
My name is Herbie Turner and I'm an MIT CS Meng student working with my friend PhD student Ruben Castro, whose undergrad MechE thesis is cited in your paper. Together, we are working on a class project using your dataset and infrastructure. We're interested in including volume (velocity) in our reward function. Right now, we have some basic formulas for MIDI note velocity as a function of key angular velocity at the time of activation but I'm new to RL and using mujoco and am struggling to get the key angular velocity. I tried using qvel but it appears to be 0 for every timestep when running the example action sequence. Does anyone have suggestions?

**Comment by hturner08** [comment]
Resolved, I added an observable that returns physics.bind(self._entity.joints).qvel

**Comment by kevinzakka** [comment]
Hi @hturner08, happy to hear you're working on this. Let me know if I can be of any assistance. It would be great to add velocity support to the benchmark. Let me know if we can work together on a PR once you finish your class project. Cheers!
